# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VakuraamatStructureIdUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[String, VakuraamatStructure] = {}

func _init(p_local_db: LocalDatabase) -> void:
	_table_name = &"structure"
	_field_name = &"id"
	_connect_cache_to_db(_cache, p_local_db)

func find(col_val: String) -> VakuraamatStructure:
	return _cache.get(col_val, null)
