# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VakuraamatObligationTable extends _ModuleTable

signal inserted(row: VakuraamatObligation)
signal updated(old_row: VakuraamatObligation, new_row: VakuraamatObligation)
signal deleted(row: VakuraamatObligation)

var id: VakuraamatObligationIdUniqueIndex
var player_id: VakuraamatObligationPlayerIdBTreeIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"obligation"
	id = VakuraamatObligationIdUniqueIndex.new(p_local_db)
	player_id = VakuraamatObligationPlayerIdBTreeIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VakuraamatObligation]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VakuraamatObligation] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VakuraamatObligation]:
	var rows: Array = super(predicate)
	var typed_array: Array[VakuraamatObligation] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VakuraamatObligation:
	return super(predicate) as VakuraamatObligation

func find_by(field: StringName, value: Variant) -> Array[VakuraamatObligation]:
	var rows: Array = super(field, value)
	var typed_array: Array[VakuraamatObligation] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VakuraamatObligation:
	return super(field, value) as VakuraamatObligation

func find_by_id(value: int) -> Array[VakuraamatObligation]:
	var row: VakuraamatObligation = id.find(value)
	var result: Array[VakuraamatObligation] = []
	if row != null:
		result.append(row)
	return result

func first_by_id(value: int) -> VakuraamatObligation:
	return id.find(value)

func find_by_player_id(value: int) -> Array[VakuraamatObligation]:
	return player_id.filter(value)

func first_by_player_id(value: int) -> VakuraamatObligation:
	return player_id._first_row(value) as VakuraamatObligation

func find_by_kind(value: String) -> Array[VakuraamatObligation]:
	return find_by(&"kind", value)

func first_by_kind(value: String) -> VakuraamatObligation:
	return first_by(&"kind", value)

func find_by_tunnus(value: String) -> Array[VakuraamatObligation]:
	return find_by(&"tunnus", value)

func first_by_tunnus(value: String) -> VakuraamatObligation:
	return first_by(&"tunnus", value)

func find_by_amount(value: int) -> Array[VakuraamatObligation]:
	return find_by(&"amount", value)

func first_by_amount(value: int) -> VakuraamatObligation:
	return first_by(&"amount", value)

func find_by_due_month(value: int) -> Array[VakuraamatObligation]:
	return find_by(&"due_month", value)

func first_by_due_month(value: int) -> VakuraamatObligation:
	return first_by(&"due_month", value)

func find_by_paid(value: bool) -> Array[VakuraamatObligation]:
	return find_by(&"paid", value)

func first_by_paid(value: bool) -> VakuraamatObligation:
	return first_by(&"paid", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VakuraamatObligation)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VakuraamatObligation, new_row as VakuraamatObligation)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VakuraamatObligation)
