# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VakuraamatImprovementTable extends _ModuleTable

signal inserted(row: VakuraamatImprovement)
signal updated(old_row: VakuraamatImprovement, new_row: VakuraamatImprovement)
signal deleted(row: VakuraamatImprovement)

var id: VakuraamatImprovementIdUniqueIndex
var tunnus: VakuraamatImprovementTunnusBTreeIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"improvement"
	id = VakuraamatImprovementIdUniqueIndex.new(p_local_db)
	tunnus = VakuraamatImprovementTunnusBTreeIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VakuraamatImprovement]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VakuraamatImprovement] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VakuraamatImprovement]:
	var rows: Array = super(predicate)
	var typed_array: Array[VakuraamatImprovement] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VakuraamatImprovement:
	return super(predicate) as VakuraamatImprovement

func find_by(field: StringName, value: Variant) -> Array[VakuraamatImprovement]:
	var rows: Array = super(field, value)
	var typed_array: Array[VakuraamatImprovement] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VakuraamatImprovement:
	return super(field, value) as VakuraamatImprovement

func find_by_id(value: int) -> Array[VakuraamatImprovement]:
	var row: VakuraamatImprovement = id.find(value)
	var result: Array[VakuraamatImprovement] = []
	if row != null:
		result.append(row)
	return result

func first_by_id(value: int) -> VakuraamatImprovement:
	return id.find(value)

func find_by_tunnus(value: String) -> Array[VakuraamatImprovement]:
	return tunnus.filter(value)

func first_by_tunnus(value: String) -> VakuraamatImprovement:
	return tunnus._first_row(value) as VakuraamatImprovement

func find_by_structure_id(value: String) -> Array[VakuraamatImprovement]:
	return find_by(&"structure_id", value)

func first_by_structure_id(value: String) -> VakuraamatImprovement:
	return first_by(&"structure_id", value)

func find_by_player_id(value: int) -> Array[VakuraamatImprovement]:
	return find_by(&"player_id", value)

func first_by_player_id(value: int) -> VakuraamatImprovement:
	return first_by(&"player_id", value)

func find_by_built_month(value: int) -> Array[VakuraamatImprovement]:
	return find_by(&"built_month", value)

func first_by_built_month(value: int) -> VakuraamatImprovement:
	return first_by(&"built_month", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VakuraamatImprovement)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VakuraamatImprovement, new_row as VakuraamatImprovement)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VakuraamatImprovement)
