# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VakuraamatParcelTable extends _ModuleTable

signal inserted(row: VakuraamatParcel)
signal updated(old_row: VakuraamatParcel, new_row: VakuraamatParcel)
signal deleted(row: VakuraamatParcel)

var tunnus: VakuraamatParcelTunnusUniqueIndex
var owner_id: VakuraamatParcelOwnerIdBTreeIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"parcel"
	tunnus = VakuraamatParcelTunnusUniqueIndex.new(p_local_db)
	owner_id = VakuraamatParcelOwnerIdBTreeIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VakuraamatParcel]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VakuraamatParcel] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VakuraamatParcel]:
	var rows: Array = super(predicate)
	var typed_array: Array[VakuraamatParcel] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VakuraamatParcel:
	return super(predicate) as VakuraamatParcel

func find_by(field: StringName, value: Variant) -> Array[VakuraamatParcel]:
	var rows: Array = super(field, value)
	var typed_array: Array[VakuraamatParcel] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VakuraamatParcel:
	return super(field, value) as VakuraamatParcel

func find_by_tunnus(value: String) -> Array[VakuraamatParcel]:
	var row: VakuraamatParcel = tunnus.find(value)
	var result: Array[VakuraamatParcel] = []
	if row != null:
		result.append(row)
	return result

func first_by_tunnus(value: String) -> VakuraamatParcel:
	return tunnus.find(value)

func find_by_address(value: String) -> Array[VakuraamatParcel]:
	return find_by(&"address", value)

func first_by_address(value: String) -> VakuraamatParcel:
	return first_by(&"address", value)

func find_by_purpose(value: String) -> Array[VakuraamatParcel]:
	return find_by(&"purpose", value)

func first_by_purpose(value: String) -> VakuraamatParcel:
	return first_by(&"purpose", value)

func find_by_area(value: int) -> Array[VakuraamatParcel]:
	return find_by(&"area", value)

func first_by_area(value: int) -> VakuraamatParcel:
	return first_by(&"area", value)

func find_by_land_value(value: int) -> Array[VakuraamatParcel]:
	return find_by(&"land_value", value)

func first_by_land_value(value: int) -> VakuraamatParcel:
	return first_by(&"land_value", value)

func find_by_price(value: int) -> Array[VakuraamatParcel]:
	return find_by(&"price", value)

func first_by_price(value: int) -> VakuraamatParcel:
	return first_by(&"price", value)

func find_by_rent_month(value: int) -> Array[VakuraamatParcel]:
	return find_by(&"rent_month", value)

func first_by_rent_month(value: int) -> VakuraamatParcel:
	return first_by(&"rent_month", value)

func find_by_owner_id(value: int) -> Array[VakuraamatParcel]:
	return owner_id.filter(value)

func first_by_owner_id(value: int) -> VakuraamatParcel:
	return owner_id._first_row(value) as VakuraamatParcel

func find_by_owner_name(value: String) -> Array[VakuraamatParcel]:
	return find_by(&"owner_name", value)

func first_by_owner_name(value: String) -> VakuraamatParcel:
	return first_by(&"owner_name", value)

func find_by_for_sale(value: bool) -> Array[VakuraamatParcel]:
	return find_by(&"for_sale", value)

func first_by_for_sale(value: bool) -> VakuraamatParcel:
	return first_by(&"for_sale", value)

func find_by_sellable(value: bool) -> Array[VakuraamatParcel]:
	return find_by(&"sellable", value)

func first_by_sellable(value: bool) -> VakuraamatParcel:
	return first_by(&"sellable", value)

func find_by_x(value: float) -> Array[VakuraamatParcel]:
	return find_by(&"x", value)

func first_by_x(value: float) -> VakuraamatParcel:
	return first_by(&"x", value)

func find_by_z(value: float) -> Array[VakuraamatParcel]:
	return find_by(&"z", value)

func first_by_z(value: float) -> VakuraamatParcel:
	return first_by(&"z", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VakuraamatParcel)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VakuraamatParcel, new_row as VakuraamatParcel)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VakuraamatParcel)
