# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VakuraamatEventTable extends _ModuleTable

signal inserted(row: VakuraamatEvent)
signal updated(old_row: VakuraamatEvent, new_row: VakuraamatEvent)
signal deleted(row: VakuraamatEvent)

var id: VakuraamatEventIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"event"
	id = VakuraamatEventIdUniqueIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VakuraamatEvent]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VakuraamatEvent] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VakuraamatEvent]:
	var rows: Array = super(predicate)
	var typed_array: Array[VakuraamatEvent] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VakuraamatEvent:
	return super(predicate) as VakuraamatEvent

func find_by(field: StringName, value: Variant) -> Array[VakuraamatEvent]:
	var rows: Array = super(field, value)
	var typed_array: Array[VakuraamatEvent] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VakuraamatEvent:
	return super(field, value) as VakuraamatEvent

func find_by_id(value: int) -> Array[VakuraamatEvent]:
	var row: VakuraamatEvent = id.find(value)
	var result: Array[VakuraamatEvent] = []
	if row != null:
		result.append(row)
	return result

func first_by_id(value: int) -> VakuraamatEvent:
	return id.find(value)

func find_by_month(value: int) -> Array[VakuraamatEvent]:
	return find_by(&"month", value)

func first_by_month(value: int) -> VakuraamatEvent:
	return first_by(&"month", value)

func find_by_kind(value: String) -> Array[VakuraamatEvent]:
	return find_by(&"kind", value)

func first_by_kind(value: String) -> VakuraamatEvent:
	return first_by(&"kind", value)

func find_by_title(value: String) -> Array[VakuraamatEvent]:
	return find_by(&"title", value)

func first_by_title(value: String) -> VakuraamatEvent:
	return first_by(&"title", value)

func find_by_source(value: String) -> Array[VakuraamatEvent]:
	return find_by(&"source", value)

func first_by_source(value: String) -> VakuraamatEvent:
	return first_by(&"source", value)

func find_by_link(value: String) -> Array[VakuraamatEvent]:
	return find_by(&"link", value)

func first_by_link(value: String) -> VakuraamatEvent:
	return first_by(&"link", value)

func find_by_tunnus(value: String) -> Array[VakuraamatEvent]:
	return find_by(&"tunnus", value)

func first_by_tunnus(value: String) -> VakuraamatEvent:
	return first_by(&"tunnus", value)

func find_by_actor_id(value: int) -> Array[VakuraamatEvent]:
	return find_by(&"actor_id", value)

func first_by_actor_id(value: int) -> VakuraamatEvent:
	return first_by(&"actor_id", value)

func find_by_amount(value: int) -> Array[VakuraamatEvent]:
	return find_by(&"amount", value)

func first_by_amount(value: int) -> VakuraamatEvent:
	return first_by(&"amount", value)

func find_by_published(value: String) -> Array[VakuraamatEvent]:
	return find_by(&"published", value)

func first_by_published(value: String) -> VakuraamatEvent:
	return first_by(&"published", value)

func find_by_at(value: int) -> Array[VakuraamatEvent]:
	return find_by(&"at", value)

func first_by_at(value: int) -> VakuraamatEvent:
	return first_by(&"at", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VakuraamatEvent)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VakuraamatEvent, new_row as VakuraamatEvent)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VakuraamatEvent)
