# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VakuraamatStructureTable extends _ModuleTable

signal inserted(row: VakuraamatStructure)
signal updated(old_row: VakuraamatStructure, new_row: VakuraamatStructure)
signal deleted(row: VakuraamatStructure)

var id: VakuraamatStructureIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"structure"
	id = VakuraamatStructureIdUniqueIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VakuraamatStructure]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VakuraamatStructure] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VakuraamatStructure]:
	var rows: Array = super(predicate)
	var typed_array: Array[VakuraamatStructure] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VakuraamatStructure:
	return super(predicate) as VakuraamatStructure

func find_by(field: StringName, value: Variant) -> Array[VakuraamatStructure]:
	var rows: Array = super(field, value)
	var typed_array: Array[VakuraamatStructure] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VakuraamatStructure:
	return super(field, value) as VakuraamatStructure

func find_by_id(value: String) -> Array[VakuraamatStructure]:
	var row: VakuraamatStructure = id.find(value)
	var result: Array[VakuraamatStructure] = []
	if row != null:
		result.append(row)
	return result

func first_by_id(value: String) -> VakuraamatStructure:
	return id.find(value)

func find_by_cost(value: int) -> Array[VakuraamatStructure]:
	return find_by(&"cost", value)

func first_by_cost(value: int) -> VakuraamatStructure:
	return first_by(&"cost", value)

func find_by_rent_bonus(value: int) -> Array[VakuraamatStructure]:
	return find_by(&"rent_bonus", value)

func first_by_rent_bonus(value: int) -> VakuraamatStructure:
	return first_by(&"rent_bonus", value)

func find_by_requires(value: String) -> Array[VakuraamatStructure]:
	return find_by(&"requires", value)

func first_by_requires(value: String) -> VakuraamatStructure:
	return first_by(&"requires", value)

func find_by_purposes(value: String) -> Array[VakuraamatStructure]:
	return find_by(&"purposes", value)

func first_by_purposes(value: String) -> VakuraamatStructure:
	return first_by(&"purposes", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VakuraamatStructure)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VakuraamatStructure, new_row as VakuraamatStructure)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VakuraamatStructure)
