# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VakuraamatTownTable extends _ModuleTable

signal inserted(row: VakuraamatTown)
signal updated(old_row: VakuraamatTown, new_row: VakuraamatTown)
signal deleted(row: VakuraamatTown)

var id: VakuraamatTownIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"town"
	id = VakuraamatTownIdUniqueIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VakuraamatTown]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VakuraamatTown] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VakuraamatTown]:
	var rows: Array = super(predicate)
	var typed_array: Array[VakuraamatTown] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VakuraamatTown:
	return super(predicate) as VakuraamatTown

func find_by(field: StringName, value: Variant) -> Array[VakuraamatTown]:
	var rows: Array = super(field, value)
	var typed_array: Array[VakuraamatTown] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VakuraamatTown:
	return super(field, value) as VakuraamatTown

func find_by_id(value: int) -> Array[VakuraamatTown]:
	var row: VakuraamatTown = id.find(value)
	var result: Array[VakuraamatTown] = []
	if row != null:
		result.append(row)
	return result

func first_by_id(value: int) -> VakuraamatTown:
	return id.find(value)

func find_by_pack_id(value: String) -> Array[VakuraamatTown]:
	return find_by(&"pack_id", value)

func first_by_pack_id(value: String) -> VakuraamatTown:
	return first_by(&"pack_id", value)

func find_by_pack_hash(value: String) -> Array[VakuraamatTown]:
	return find_by(&"pack_hash", value)

func first_by_pack_hash(value: String) -> VakuraamatTown:
	return first_by(&"pack_hash", value)

func find_by_month(value: int) -> Array[VakuraamatTown]:
	return find_by(&"month", value)

func first_by_month(value: int) -> VakuraamatTown:
	return first_by(&"month", value)

func find_by_seconds_per_month(value: int) -> Array[VakuraamatTown]:
	return find_by(&"seconds_per_month", value)

func first_by_seconds_per_month(value: int) -> VakuraamatTown:
	return first_by(&"seconds_per_month", value)

func find_by_price_index_permille(value: int) -> Array[VakuraamatTown]:
	return find_by(&"price_index_permille", value)

func first_by_price_index_permille(value: int) -> VakuraamatTown:
	return first_by(&"price_index_permille", value)

func find_by_seeded(value: bool) -> Array[VakuraamatTown]:
	return find_by(&"seeded", value)

func first_by_seeded(value: bool) -> VakuraamatTown:
	return first_by(&"seeded", value)

func find_by_debug(value: bool) -> Array[VakuraamatTown]:
	return find_by(&"debug", value)

func first_by_debug(value: bool) -> VakuraamatTown:
	return first_by(&"debug", value)

func find_by_admin(value: PackedByteArray) -> Array[VakuraamatTown]:
	return find_by(&"admin", value)

func first_by_admin(value: PackedByteArray) -> VakuraamatTown:
	return first_by(&"admin", value)

func find_by_created(value: int) -> Array[VakuraamatTown]:
	return find_by(&"created", value)

func first_by_created(value: int) -> VakuraamatTown:
	return first_by(&"created", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VakuraamatTown)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VakuraamatTown, new_row as VakuraamatTown)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VakuraamatTown)
