# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VakuraamatBidTable extends _ModuleTable

signal inserted(row: VakuraamatBid)
signal updated(old_row: VakuraamatBid, new_row: VakuraamatBid)
signal deleted(row: VakuraamatBid)

var id: VakuraamatBidIdUniqueIndex
var tunnus: VakuraamatBidTunnusBTreeIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"bid"
	id = VakuraamatBidIdUniqueIndex.new(p_local_db)
	tunnus = VakuraamatBidTunnusBTreeIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VakuraamatBid]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VakuraamatBid] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VakuraamatBid]:
	var rows: Array = super(predicate)
	var typed_array: Array[VakuraamatBid] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VakuraamatBid:
	return super(predicate) as VakuraamatBid

func find_by(field: StringName, value: Variant) -> Array[VakuraamatBid]:
	var rows: Array = super(field, value)
	var typed_array: Array[VakuraamatBid] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VakuraamatBid:
	return super(field, value) as VakuraamatBid

func find_by_id(value: int) -> Array[VakuraamatBid]:
	var row: VakuraamatBid = id.find(value)
	var result: Array[VakuraamatBid] = []
	if row != null:
		result.append(row)
	return result

func first_by_id(value: int) -> VakuraamatBid:
	return id.find(value)

func find_by_tunnus(value: String) -> Array[VakuraamatBid]:
	return tunnus.filter(value)

func first_by_tunnus(value: String) -> VakuraamatBid:
	return tunnus._first_row(value) as VakuraamatBid

func find_by_bidder_id(value: int) -> Array[VakuraamatBid]:
	return find_by(&"bidder_id", value)

func first_by_bidder_id(value: int) -> VakuraamatBid:
	return first_by(&"bidder_id", value)

func find_by_bidder_name(value: String) -> Array[VakuraamatBid]:
	return find_by(&"bidder_name", value)

func first_by_bidder_name(value: String) -> VakuraamatBid:
	return first_by(&"bidder_name", value)

func find_by_amount(value: int) -> Array[VakuraamatBid]:
	return find_by(&"amount", value)

func first_by_amount(value: int) -> VakuraamatBid:
	return first_by(&"amount", value)

func find_by_placed_month(value: int) -> Array[VakuraamatBid]:
	return find_by(&"placed_month", value)

func first_by_placed_month(value: int) -> VakuraamatBid:
	return first_by(&"placed_month", value)

func find_by_expires_month(value: int) -> Array[VakuraamatBid]:
	return find_by(&"expires_month", value)

func first_by_expires_month(value: int) -> VakuraamatBid:
	return first_by(&"expires_month", value)

func find_by_status(value: int) -> Array[VakuraamatBid]:
	return find_by(&"status", value)

func first_by_status(value: int) -> VakuraamatBid:
	return first_by(&"status", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VakuraamatBid)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VakuraamatBid, new_row as VakuraamatBid)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VakuraamatBid)
