# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VakuraamatPresencePlayerIdUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[int, VakuraamatPresence] = {}

func _init(p_local_db: LocalDatabase) -> void:
	_table_name = &"presence"
	_field_name = &"player_id"
	_connect_cache_to_db(_cache, p_local_db)

func find(col_val: int) -> VakuraamatPresence:
	return _cache.get(col_val, null)
