# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VakuraamatPlayerIdentityUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[PackedByteArray, VakuraamatPlayer] = {}

func _init(p_local_db: LocalDatabase) -> void:
	_table_name = &"player"
	_field_name = &"identity"
	_connect_cache_to_db(_cache, p_local_db)

func find(col_val: PackedByteArray) -> VakuraamatPlayer:
	return _cache.get(col_val, null)
