# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VakuraamatPlayerTable extends _ModuleTable

signal inserted(row: VakuraamatPlayer)
signal updated(old_row: VakuraamatPlayer, new_row: VakuraamatPlayer)
signal deleted(row: VakuraamatPlayer)

var id: VakuraamatPlayerIdUniqueIndex
var identity: VakuraamatPlayerIdentityUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"player"
	id = VakuraamatPlayerIdUniqueIndex.new(p_local_db)
	identity = VakuraamatPlayerIdentityUniqueIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VakuraamatPlayer]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VakuraamatPlayer] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VakuraamatPlayer]:
	var rows: Array = super(predicate)
	var typed_array: Array[VakuraamatPlayer] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VakuraamatPlayer:
	return super(predicate) as VakuraamatPlayer

func find_by(field: StringName, value: Variant) -> Array[VakuraamatPlayer]:
	var rows: Array = super(field, value)
	var typed_array: Array[VakuraamatPlayer] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VakuraamatPlayer:
	return super(field, value) as VakuraamatPlayer

func find_by_id(value: int) -> Array[VakuraamatPlayer]:
	var row: VakuraamatPlayer = id.find(value)
	var result: Array[VakuraamatPlayer] = []
	if row != null:
		result.append(row)
	return result

func first_by_id(value: int) -> VakuraamatPlayer:
	return id.find(value)

func find_by_identity(value: PackedByteArray) -> Array[VakuraamatPlayer]:
	var row: VakuraamatPlayer = identity.find(value)
	var result: Array[VakuraamatPlayer] = []
	if row != null:
		result.append(row)
	return result

func first_by_identity(value: PackedByteArray) -> VakuraamatPlayer:
	return identity.find(value)

func find_by_name(value: String) -> Array[VakuraamatPlayer]:
	return find_by(&"name", value)

func first_by_name(value: String) -> VakuraamatPlayer:
	return first_by(&"name", value)

func find_by_cash(value: int) -> Array[VakuraamatPlayer]:
	return find_by(&"cash", value)

func first_by_cash(value: int) -> VakuraamatPlayer:
	return first_by(&"cash", value)

func find_by_favours(value: int) -> Array[VakuraamatPlayer]:
	return find_by(&"favours", value)

func first_by_favours(value: int) -> VakuraamatPlayer:
	return first_by(&"favours", value)

func find_by_heat(value: int) -> Array[VakuraamatPlayer]:
	return find_by(&"heat", value)

func first_by_heat(value: int) -> VakuraamatPlayer:
	return first_by(&"heat", value)

func find_by_reputation(value: int) -> Array[VakuraamatPlayer]:
	return find_by(&"reputation", value)

func first_by_reputation(value: int) -> VakuraamatPlayer:
	return first_by(&"reputation", value)

func find_by_online(value: bool) -> Array[VakuraamatPlayer]:
	return find_by(&"online", value)

func first_by_online(value: bool) -> VakuraamatPlayer:
	return first_by(&"online", value)

func find_by_joined_month(value: int) -> Array[VakuraamatPlayer]:
	return find_by(&"joined_month", value)

func first_by_joined_month(value: int) -> VakuraamatPlayer:
	return first_by(&"joined_month", value)

func find_by_last_seen(value: int) -> Array[VakuraamatPlayer]:
	return find_by(&"last_seen", value)

func first_by_last_seen(value: int) -> VakuraamatPlayer:
	return first_by(&"last_seen", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VakuraamatPlayer)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VakuraamatPlayer, new_row as VakuraamatPlayer)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VakuraamatPlayer)
