# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VakuraamatParcelTunnusUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[String, VakuraamatParcel] = {}

func _init(p_local_db: LocalDatabase) -> void:
	_table_name = &"parcel"
	_field_name = &"tunnus"
	_connect_cache_to_db(_cache, p_local_db)

func find(col_val: String) -> VakuraamatParcel:
	return _cache.get(col_val, null)
