# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VakuraamatTenantTable extends _ModuleTable

signal inserted(row: VakuraamatTenant)
signal updated(old_row: VakuraamatTenant, new_row: VakuraamatTenant)
signal deleted(row: VakuraamatTenant)

var id: VakuraamatTenantIdUniqueIndex
var tunnus: VakuraamatTenantTunnusBTreeIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"tenant"
	id = VakuraamatTenantIdUniqueIndex.new(p_local_db)
	tunnus = VakuraamatTenantTunnusBTreeIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VakuraamatTenant]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VakuraamatTenant] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VakuraamatTenant]:
	var rows: Array = super(predicate)
	var typed_array: Array[VakuraamatTenant] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VakuraamatTenant:
	return super(predicate) as VakuraamatTenant

func find_by(field: StringName, value: Variant) -> Array[VakuraamatTenant]:
	var rows: Array = super(field, value)
	var typed_array: Array[VakuraamatTenant] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VakuraamatTenant:
	return super(field, value) as VakuraamatTenant

func find_by_id(value: int) -> Array[VakuraamatTenant]:
	var row: VakuraamatTenant = id.find(value)
	var result: Array[VakuraamatTenant] = []
	if row != null:
		result.append(row)
	return result

func first_by_id(value: int) -> VakuraamatTenant:
	return id.find(value)

func find_by_tunnus(value: String) -> Array[VakuraamatTenant]:
	return tunnus.filter(value)

func first_by_tunnus(value: String) -> VakuraamatTenant:
	return tunnus._first_row(value) as VakuraamatTenant

func find_by_name(value: String) -> Array[VakuraamatTenant]:
	return find_by(&"name", value)

func first_by_name(value: String) -> VakuraamatTenant:
	return first_by(&"name", value)

func find_by_registry_code(value: String) -> Array[VakuraamatTenant]:
	return find_by(&"registry_code", value)

func first_by_registry_code(value: String) -> VakuraamatTenant:
	return first_by(&"registry_code", value)

func find_by_legal_form(value: String) -> Array[VakuraamatTenant]:
	return find_by(&"legal_form", value)

func first_by_legal_form(value: String) -> VakuraamatTenant:
	return first_by(&"legal_form", value)

func find_by_status(value: String) -> Array[VakuraamatTenant]:
	return find_by(&"status", value)

func first_by_status(value: String) -> VakuraamatTenant:
	return first_by(&"status", value)

func find_by_since(value: String) -> Array[VakuraamatTenant]:
	return find_by(&"since", value)

func first_by_since(value: String) -> VakuraamatTenant:
	return first_by(&"since", value)

func find_by_arrears(value: int) -> Array[VakuraamatTenant]:
	return find_by(&"arrears", value)

func first_by_arrears(value: int) -> VakuraamatTenant:
	return first_by(&"arrears", value)

func find_by_sector(value: String) -> Array[VakuraamatTenant]:
	return find_by(&"sector", value)

func first_by_sector(value: String) -> VakuraamatTenant:
	return first_by(&"sector", value)

func find_by_employees(value: int) -> Array[VakuraamatTenant]:
	return find_by(&"employees", value)

func first_by_employees(value: int) -> VakuraamatTenant:
	return first_by(&"employees", value)

func find_by_turnover(value: int) -> Array[VakuraamatTenant]:
	return find_by(&"turnover", value)

func first_by_turnover(value: int) -> VakuraamatTenant:
	return first_by(&"turnover", value)

func find_by_health(value: String) -> Array[VakuraamatTenant]:
	return find_by(&"health", value)

func first_by_health(value: String) -> VakuraamatTenant:
	return first_by(&"health", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VakuraamatTenant)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VakuraamatTenant, new_row as VakuraamatTenant)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VakuraamatTenant)
