# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VakuraamatPresenceTable extends _ModuleTable

signal inserted(row: VakuraamatPresence)
signal updated(old_row: VakuraamatPresence, new_row: VakuraamatPresence)
signal deleted(row: VakuraamatPresence)

var player_id: VakuraamatPresencePlayerIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"presence"
	player_id = VakuraamatPresencePlayerIdUniqueIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[VakuraamatPresence]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[VakuraamatPresence] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[VakuraamatPresence]:
	var rows: Array = super(predicate)
	var typed_array: Array[VakuraamatPresence] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> VakuraamatPresence:
	return super(predicate) as VakuraamatPresence

func find_by(field: StringName, value: Variant) -> Array[VakuraamatPresence]:
	var rows: Array = super(field, value)
	var typed_array: Array[VakuraamatPresence] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> VakuraamatPresence:
	return super(field, value) as VakuraamatPresence

func find_by_player_id(value: int) -> Array[VakuraamatPresence]:
	var row: VakuraamatPresence = player_id.find(value)
	var result: Array[VakuraamatPresence] = []
	if row != null:
		result.append(row)
	return result

func first_by_player_id(value: int) -> VakuraamatPresence:
	return player_id.find(value)

func find_by_x(value: float) -> Array[VakuraamatPresence]:
	return find_by(&"x", value)

func first_by_x(value: float) -> VakuraamatPresence:
	return first_by(&"x", value)

func find_by_z(value: float) -> Array[VakuraamatPresence]:
	return find_by(&"z", value)

func first_by_z(value: float) -> VakuraamatPresence:
	return first_by(&"z", value)

func find_by_yaw(value: float) -> Array[VakuraamatPresence]:
	return find_by(&"yaw", value)

func first_by_yaw(value: float) -> VakuraamatPresence:
	return first_by(&"yaw", value)

func find_by_updated_(value: int) -> Array[VakuraamatPresence]:
	return find_by(&"updated_", value)

func first_by_updated_(value: int) -> VakuraamatPresence:
	return first_by(&"updated_", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as VakuraamatPresence)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as VakuraamatPresence, new_row as VakuraamatPresence)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as VakuraamatPresence)
