# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VakuraamatTenant extends _ModuleTableType

const module_name : String = "Vakuraamat"
const table_names: Array[StringName] = [&'tenant']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"tunnus": &"string", &"name": &"string", &"registry_code": &"string", &"legal_form": &"string", &"status": &"string", &"since": &"string", &"arrears": &"u64" }

@export var id: int
@export var tunnus: String
@export var name: String
@export var registry_code: String
@export var legal_form: String
@export var status: String
@export var since: String
@export var arrears: int

## 0. id: int[br]
## 1. tunnus: String[br]
## 2. name: String[br]
## 3. registry_code: String[br]
## 4. legal_form: String[br]
## 5. status: String[br]
## 6. since: String[br]
## 7. arrears: int[br]
static func create(p_id: int, p_tunnus: String, p_name: String, p_registry_code: String, p_legal_form: String, p_status: String, p_since: String, p_arrears: int) -> VakuraamatTenant:
	var result: VakuraamatTenant = VakuraamatTenant.new()
	result.id = p_id
	result.tunnus = p_tunnus
	result.name = p_name
	result.registry_code = p_registry_code
	result.legal_form = p_legal_form
	result.status = p_status
	result.since = p_since
	result.arrears = p_arrears
	return result
