# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VakuraamatObligation extends _ModuleTableType

const module_name : String = "Vakuraamat"
const table_names: Array[StringName] = [&'obligation']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"player_id": &"u64", &"kind": &"string", &"tunnus": &"string", &"amount": &"u64", &"due_month": &"u32", &"paid": &"bool" }

@export var id: int
@export var player_id: int
@export var kind: String
@export var tunnus: String
@export var amount: int
@export var due_month: int
@export var paid: bool

## 0. id: int[br]
## 1. player_id: int[br]
## 2. kind: String[br]
## 3. tunnus: String[br]
## 4. amount: int[br]
## 5. due_month: int[br]
## 6. paid: bool[br]
static func create(p_id: int, p_player_id: int, p_kind: String, p_tunnus: String, p_amount: int, p_due_month: int, p_paid: bool) -> VakuraamatObligation:
	var result: VakuraamatObligation = VakuraamatObligation.new()
	result.id = p_id
	result.player_id = p_player_id
	result.kind = p_kind
	result.tunnus = p_tunnus
	result.amount = p_amount
	result.due_month = p_due_month
	result.paid = p_paid
	return result
