# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VakuraamatPresence extends _ModuleTableType

const module_name : String = "Vakuraamat"
const table_names: Array[StringName] = [&'presence']
const PRIMARY_KEY: StringName = &"player_id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"player_id": &"u64", &"x": &"f32", &"z": &"f32", &"yaw": &"f32", &"updated_": &"i64" }

@export var player_id: int
@export var x: float
@export var z: float
@export var yaw: float
@export var updated_: int

## 0. player_id: int[br]
## 1. x: float[br]
## 2. z: float[br]
## 3. yaw: float[br]
## 4. updated_: int[br]
static func create(p_player_id: int, p_x: float, p_z: float, p_yaw: float, p_updated_: int) -> VakuraamatPresence:
	var result: VakuraamatPresence = VakuraamatPresence.new()
	result.player_id = p_player_id
	result.x = p_x
	result.z = p_z
	result.yaw = p_yaw
	result.updated_ = p_updated_
	return result
