# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VakuraamatTown extends _ModuleTableType

const module_name : String = "Vakuraamat"
const table_names: Array[StringName] = [&'town']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u32", &"pack_id": &"string", &"pack_hash": &"string", &"month": &"u32", &"seconds_per_month": &"u32", &"price_index_permille": &"u32", &"seeded": &"bool", &"debug": &"bool", &"admin": &"identity", &"created": &"i64" }

@export var id: int
@export var pack_id: String
@export var pack_hash: String
@export var month: int
@export var seconds_per_month: int
@export var price_index_permille: int
@export var seeded: bool
@export var debug: bool
@export var admin: PackedByteArray
@export var created: int

## 0. id: int[br]
## 1. pack_id: String[br]
## 2. pack_hash: String[br]
## 3. month: int[br]
## 4. seconds_per_month: int[br]
## 5. price_index_permille: int[br]
## 6. seeded: bool[br]
## 7. debug: bool[br]
## 8. admin: PackedByteArray[br]
## 9. created: int[br]
static func create(p_id: int, p_pack_id: String, p_pack_hash: String, p_month: int, p_seconds_per_month: int, p_price_index_permille: int, p_seeded: bool, p_debug: bool, p_admin: PackedByteArray, p_created: int) -> VakuraamatTown:
	var result: VakuraamatTown = VakuraamatTown.new()
	result.id = p_id
	result.pack_id = p_pack_id
	result.pack_hash = p_pack_hash
	result.month = p_month
	result.seconds_per_month = p_seconds_per_month
	result.price_index_permille = p_price_index_permille
	result.seeded = p_seeded
	result.debug = p_debug
	result.admin = p_admin
	result.created = p_created
	return result
