# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VakuraamatPlayer extends _ModuleTableType

const module_name : String = "Vakuraamat"
const table_names: Array[StringName] = [&'player']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"identity": &"identity", &"name": &"string", &"cash": &"i64", &"favours": &"i32", &"heat": &"i32", &"reputation": &"i32", &"online": &"bool", &"joined_month": &"u32", &"last_seen": &"i64" }

@export var id: int
@export var identity: PackedByteArray
@export var name: String
@export var cash: int
@export var favours: int
@export var heat: int
@export var reputation: int
@export var online: bool
@export var joined_month: int
@export var last_seen: int

## 0. id: int[br]
## 1. identity: PackedByteArray[br]
## 2. name: String[br]
## 3. cash: int[br]
## 4. favours: int[br]
## 5. heat: int[br]
## 6. reputation: int[br]
## 7. online: bool[br]
## 8. joined_month: int[br]
## 9. last_seen: int[br]
static func create(p_id: int, p_identity: PackedByteArray, p_name: String, p_cash: int, p_favours: int, p_heat: int, p_reputation: int, p_online: bool, p_joined_month: int, p_last_seen: int) -> VakuraamatPlayer:
	var result: VakuraamatPlayer = VakuraamatPlayer.new()
	result.id = p_id
	result.identity = p_identity
	result.name = p_name
	result.cash = p_cash
	result.favours = p_favours
	result.heat = p_heat
	result.reputation = p_reputation
	result.online = p_online
	result.joined_month = p_joined_month
	result.last_seen = p_last_seen
	return result
