# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VakuraamatImprovement extends _ModuleTableType

const module_name : String = "Vakuraamat"
const table_names: Array[StringName] = [&'improvement']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"tunnus": &"string", &"structure_id": &"string", &"player_id": &"u64", &"built_month": &"u32" }

@export var id: int
@export var tunnus: String
@export var structure_id: String
@export var player_id: int
@export var built_month: int

## 0. id: int[br]
## 1. tunnus: String[br]
## 2. structure_id: String[br]
## 3. player_id: int[br]
## 4. built_month: int[br]
static func create(p_id: int, p_tunnus: String, p_structure_id: String, p_player_id: int, p_built_month: int) -> VakuraamatImprovement:
	var result: VakuraamatImprovement = VakuraamatImprovement.new()
	result.id = p_id
	result.tunnus = p_tunnus
	result.structure_id = p_structure_id
	result.player_id = p_player_id
	result.built_month = p_built_month
	return result
