# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VakuraamatBid extends _ModuleTableType

const module_name : String = "Vakuraamat"
const table_names: Array[StringName] = [&'bid']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"tunnus": &"string", &"bidder_id": &"u64", &"bidder_name": &"string", &"amount": &"u64", &"placed_month": &"u32", &"expires_month": &"u32", &"status": &"u8" }

@export var id: int
@export var tunnus: String
@export var bidder_id: int
@export var bidder_name: String
@export var amount: int
@export var placed_month: int
@export var expires_month: int
@export var status: int

## 0. id: int[br]
## 1. tunnus: String[br]
## 2. bidder_id: int[br]
## 3. bidder_name: String[br]
## 4. amount: int[br]
## 5. placed_month: int[br]
## 6. expires_month: int[br]
## 7. status: int[br]
static func create(p_id: int, p_tunnus: String, p_bidder_id: int, p_bidder_name: String, p_amount: int, p_placed_month: int, p_expires_month: int, p_status: int) -> VakuraamatBid:
	var result: VakuraamatBid = VakuraamatBid.new()
	result.id = p_id
	result.tunnus = p_tunnus
	result.bidder_id = p_bidder_id
	result.bidder_name = p_bidder_name
	result.amount = p_amount
	result.placed_month = p_placed_month
	result.expires_month = p_expires_month
	result.status = p_status
	return result
