# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VakuraamatEconomyConfig extends _ModuleTableType

const module_name : String = "Vakuraamat"
const table_names: Array[StringName] = []
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u32", &"starting_cash": &"i64", &"tax_rate_year_permille": &"u32", &"arrears_chance_permille": &"u32", &"arrears_chance_bad_status_permille": &"u32", &"drift_permille": &"u32", &"ai_bid_chance_permille": &"u32", &"obligation_grace_months": &"u32", &"penalty_permille": &"u32", &"families": &"string" }

@export var id: int
@export var starting_cash: int
@export var tax_rate_year_permille: int
@export var arrears_chance_permille: int
@export var arrears_chance_bad_status_permille: int
@export var drift_permille: int
@export var ai_bid_chance_permille: int
@export var obligation_grace_months: int
@export var penalty_permille: int
@export var families: Array[String] ## Array of String

## 0. id: int[br]
## 1. starting_cash: int[br]
## 2. tax_rate_year_permille: int[br]
## 3. arrears_chance_permille: int[br]
## 4. arrears_chance_bad_status_permille: int[br]
## 5. drift_permille: int[br]
## 6. ai_bid_chance_permille: int[br]
## 7. obligation_grace_months: int[br]
## 8. penalty_permille: int[br]
## 9. families: Array of String[br]
static func create(p_id: int, p_starting_cash: int, p_tax_rate_year_permille: int, p_arrears_chance_permille: int, p_arrears_chance_bad_status_permille: int, p_drift_permille: int, p_ai_bid_chance_permille: int, p_obligation_grace_months: int, p_penalty_permille: int, p_families: Array[String]) -> VakuraamatEconomyConfig:
	var result: VakuraamatEconomyConfig = VakuraamatEconomyConfig.new()
	result.id = p_id
	result.starting_cash = p_starting_cash
	result.tax_rate_year_permille = p_tax_rate_year_permille
	result.arrears_chance_permille = p_arrears_chance_permille
	result.arrears_chance_bad_status_permille = p_arrears_chance_bad_status_permille
	result.drift_permille = p_drift_permille
	result.ai_bid_chance_permille = p_ai_bid_chance_permille
	result.obligation_grace_months = p_obligation_grace_months
	result.penalty_permille = p_penalty_permille
	result.families = p_families
	return result
