# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VakuraamatStructure extends _ModuleTableType

const module_name : String = "Vakuraamat"
const table_names: Array[StringName] = [&'structure']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"string", &"cost": &"u64", &"rent_bonus": &"u64", &"requires": &"string", &"purposes": &"string" }

@export var id: String
@export var cost: int
@export var rent_bonus: int
@export var requires: String
@export var purposes: String

## 0. id: String[br]
## 1. cost: int[br]
## 2. rent_bonus: int[br]
## 3. requires: String[br]
## 4. purposes: String[br]
static func create(p_id: String, p_cost: int, p_rent_bonus: int, p_requires: String, p_purposes: String) -> VakuraamatStructure:
	var result: VakuraamatStructure = VakuraamatStructure.new()
	result.id = p_id
	result.cost = p_cost
	result.rent_bonus = p_rent_bonus
	result.requires = p_requires
	result.purposes = p_purposes
	return result
