# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VakuraamatEvent extends _ModuleTableType

const module_name : String = "Vakuraamat"
const table_names: Array[StringName] = [&'event']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"month": &"u32", &"kind": &"string", &"title": &"string", &"source": &"string", &"link": &"string", &"tunnus": &"string", &"actor_id": &"u64", &"amount": &"i64", &"published": &"string", &"at": &"i64" }

@export var id: int
@export var month: int
@export var kind: String
@export var title: String
@export var source: String
@export var link: String
@export var tunnus: String
@export var actor_id: int
@export var amount: int
@export var published: String
@export var at: int

## 0. id: int[br]
## 1. month: int[br]
## 2. kind: String[br]
## 3. title: String[br]
## 4. source: String[br]
## 5. link: String[br]
## 6. tunnus: String[br]
## 7. actor_id: int[br]
## 8. amount: int[br]
## 9. published: String[br]
## 10. at: int[br]
static func create(p_id: int, p_month: int, p_kind: String, p_title: String, p_source: String, p_link: String, p_tunnus: String, p_actor_id: int, p_amount: int, p_published: String, p_at: int) -> VakuraamatEvent:
	var result: VakuraamatEvent = VakuraamatEvent.new()
	result.id = p_id
	result.month = p_month
	result.kind = p_kind
	result.title = p_title
	result.source = p_source
	result.link = p_link
	result.tunnus = p_tunnus
	result.actor_id = p_actor_id
	result.amount = p_amount
	result.published = p_published
	result.at = p_at
	return result
