# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name VakuraamatParcel extends _ModuleTableType

const module_name : String = "Vakuraamat"
const table_names: Array[StringName] = [&'parcel']
const PRIMARY_KEY: StringName = &"tunnus"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"tunnus": &"string", &"address": &"string", &"purpose": &"string", &"area": &"u32", &"land_value": &"u64", &"price": &"u64", &"rent_month": &"u64", &"owner_id": &"u64", &"owner_name": &"string", &"for_sale": &"bool", &"sellable": &"bool", &"x": &"f32", &"z": &"f32" }

@export var tunnus: String
@export var address: String
@export var purpose: String
@export var area: int
@export var land_value: int
@export var price: int
@export var rent_month: int
@export var owner_id: int
@export var owner_name: String
@export var for_sale: bool
@export var sellable: bool
@export var x: float
@export var z: float

## 0. tunnus: String[br]
## 1. address: String[br]
## 2. purpose: String[br]
## 3. area: int[br]
## 4. land_value: int[br]
## 5. price: int[br]
## 6. rent_month: int[br]
## 7. owner_id: int[br]
## 8. owner_name: String[br]
## 9. for_sale: bool[br]
## 10. sellable: bool[br]
## 11. x: float[br]
## 12. z: float[br]
static func create(p_tunnus: String, p_address: String, p_purpose: String, p_area: int, p_land_value: int, p_price: int, p_rent_month: int, p_owner_id: int, p_owner_name: String, p_for_sale: bool, p_sellable: bool, p_x: float, p_z: float) -> VakuraamatParcel:
	var result: VakuraamatParcel = VakuraamatParcel.new()
	result.tunnus = p_tunnus
	result.address = p_address
	result.purpose = p_purpose
	result.area = p_area
	result.land_value = p_land_value
	result.price = p_price
	result.rent_month = p_rent_month
	result.owner_id = p_owner_id
	result.owner_name = p_owner_name
	result.for_sale = p_for_sale
	result.sellable = p_sellable
	result.x = p_x
	result.z = p_z
	return result
