# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VakuraamatTypes

const Bid = preload('res://spacetime_bindings/schema/types/vakuraamat_bid.gd')
const Event = preload('res://spacetime_bindings/schema/types/vakuraamat_event.gd')
const Improvement = preload('res://spacetime_bindings/schema/types/vakuraamat_improvement.gd')
const Obligation = preload('res://spacetime_bindings/schema/types/vakuraamat_obligation.gd')
const Parcel = preload('res://spacetime_bindings/schema/types/vakuraamat_parcel.gd')
const Player = preload('res://spacetime_bindings/schema/types/vakuraamat_player.gd')
const Presence = preload('res://spacetime_bindings/schema/types/vakuraamat_presence.gd')
const Structure = preload('res://spacetime_bindings/schema/types/vakuraamat_structure.gd')
const Tenant = preload('res://spacetime_bindings/schema/types/vakuraamat_tenant.gd')
const Town = preload('res://spacetime_bindings/schema/types/vakuraamat_town.gd')
