# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VakuraamatModuleDb extends RefCounted

const table_names : Array[StringName] = [&"bid", &"event", &"improvement", &"obligation", &"parcel", &"player", &"presence", &"structure", &"tenant", &"town"]

var bid: VakuraamatBidTable
var event: VakuraamatEventTable
var improvement: VakuraamatImprovementTable
var obligation: VakuraamatObligationTable
var parcel: VakuraamatParcelTable
var player: VakuraamatPlayerTable
var presence: VakuraamatPresenceTable
var structure: VakuraamatStructureTable
var tenant: VakuraamatTenantTable
var town: VakuraamatTownTable

func _init(p_local_db: LocalDatabase) -> void:
	bid = preload('res://spacetime_bindings/schema/tables/vakuraamat_bid_table.gd').new(p_local_db)
	event = preload('res://spacetime_bindings/schema/tables/vakuraamat_event_table.gd').new(p_local_db)
	improvement = preload('res://spacetime_bindings/schema/tables/vakuraamat_improvement_table.gd').new(p_local_db)
	obligation = preload('res://spacetime_bindings/schema/tables/vakuraamat_obligation_table.gd').new(p_local_db)
	parcel = preload('res://spacetime_bindings/schema/tables/vakuraamat_parcel_table.gd').new(p_local_db)
	player = preload('res://spacetime_bindings/schema/tables/vakuraamat_player_table.gd').new(p_local_db)
	presence = preload('res://spacetime_bindings/schema/tables/vakuraamat_presence_table.gd').new(p_local_db)
	structure = preload('res://spacetime_bindings/schema/tables/vakuraamat_structure_table.gd').new(p_local_db)
	tenant = preload('res://spacetime_bindings/schema/tables/vakuraamat_tenant_table.gd').new(p_local_db)
	town = preload('res://spacetime_bindings/schema/tables/vakuraamat_town_table.gd').new(p_local_db)
