# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name VakuraamatModuleReducers extends RefCounted

var _client: SpacetimeDBClient

func _init(p_client: SpacetimeDBClient) -> void:
	_client = p_client
## 0. bid_id: int [br]
func accept_bid(bid_id: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('accept_bid', [bid_id], [&'u64'], &'')

## 0. tunnus: String [br]
## 1. structure_id: String [br]
func build(tunnus: String, structure_id: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('build', [tunnus, structure_id], [&'string', &'string'], &'')

## 0. tunnus: String [br]
func buy_arrears(tunnus: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('buy_arrears', [tunnus], [&'string'], &'')

## 0. tunnus: String [br]
func buy_parcel(tunnus: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('buy_parcel', [tunnus], [&'string'], &'')

## 0. tunnus: String [br]
func clear_tenants(tunnus: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('clear_tenants', [tunnus], [&'string'], &'')

## 0. amount: int [br]
func donate(amount: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('donate', [amount], [&'u64'], &'')


func finish_seed() -> SpacetimeDBReducerCall:
	return _client.call_reducer('finish_seed', [], [], &'')

## 0. amount: int [br]
func grant_cash(amount: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('grant_cash', [amount], [&'i64'], &'')

## 0. pack_hash: String [br]
## 1. name: String [br]
func join_town(pack_hash: String, name: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('join_town', [pack_hash, name], [&'string', &'string'], &'')

## 0. tunnus: String [br]
## 1. price: int [br]
func list_for_sale(tunnus: String, price: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('list_for_sale', [tunnus, price], [&'string', &'u64'], &'')

## 0. x: float [br]
## 1. z: float [br]
## 2. yaw: float [br]
func move_to(x: float, z: float, yaw: float) -> SpacetimeDBReducerCall:
	return _client.call_reducer('move_to', [x, z, yaw], [&'f32', &'f32', &'f32'], &'')

## 0. obligation_id: int [br]
func pay_obligation(obligation_id: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('pay_obligation', [obligation_id], [&'u64'], &'')

## 0. tunnus: String [br]
## 1. amount: int [br]
func place_bid(tunnus: String, amount: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('place_bid', [tunnus, amount], [&'string', &'u64'], &'')

## 0. kind: String [br]
## 1. title: String [br]
## 2. source: String [br]
## 3. link: String [br]
## 4. tunnus: String [br]
## 5. published: String [br]
func post_event(kind: String, title: String, source: String, link: String, tunnus: String, published: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('post_event', [kind, title, source, link, tunnus, published], [&'string', &'string', &'string', &'string', &'string', &'string'], &'')

## 0. tunnus: String [br]
func press_tenant(tunnus: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('press_tenant', [tunnus], [&'string'], &'')

## 0. pack_id: String [br]
## 1. pack_hash: String [br]
## 2. seconds_per_month: int [br]
## 3. debug: bool [br]
## 4. starting_cash: int [br]
## 5. tax_rate_year_permille: int [br]
## 6. arrears_chance_permille: int [br]
## 7. arrears_chance_bad_status_permille: int [br]
## 8. drift_permille: int [br]
## 9. ai_bid_chance_permille: int [br]
## 10. obligation_grace_months: int [br]
## 11. penalty_permille: int [br]
## 12. families: String [br]
func seed_config(pack_id: String, pack_hash: String, seconds_per_month: int, debug: bool, starting_cash: int, tax_rate_year_permille: int, arrears_chance_permille: int, arrears_chance_bad_status_permille: int, drift_permille: int, ai_bid_chance_permille: int, obligation_grace_months: int, penalty_permille: int, families: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('seed_config', [pack_id, pack_hash, seconds_per_month, debug, starting_cash, tax_rate_year_permille, arrears_chance_permille, arrears_chance_bad_status_permille, drift_permille, ai_bid_chance_permille, obligation_grace_months, penalty_permille, families], [&'string', &'string', &'u32', &'bool', &'i64', &'u32', &'u32', &'u32', &'u32', &'u32', &'u32', &'u32', &'string'], &'')

## 0. tunnus: String [br]
## 1. address: String [br]
## 2. purpose: String [br]
## 3. area: int [br]
## 4. land_value: int [br]
## 5. rent_month: int [br]
## 6. owner_name: String [br]
## 7. sellable: bool [br]
## 8. x: float [br]
## 9. z: float [br]
func seed_parcel(tunnus: String, address: String, purpose: String, area: int, land_value: int, rent_month: int, owner_name: String, sellable: bool, x: float, z: float) -> SpacetimeDBReducerCall:
	return _client.call_reducer('seed_parcel', [tunnus, address, purpose, area, land_value, rent_month, owner_name, sellable, x, z], [&'string', &'string', &'string', &'u32', &'u64', &'u64', &'string', &'bool', &'f32', &'f32'], &'')

## 0. id: String [br]
## 1. cost: int [br]
## 2. rent_bonus: int [br]
## 3. requires: String [br]
## 4. purposes: String [br]
func seed_structure(id: String, cost: int, rent_bonus: int, requires: String, purposes: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('seed_structure', [id, cost, rent_bonus, requires, purposes], [&'string', &'u64', &'u64', &'string', &'string'], &'')

## 0. tunnus: String [br]
## 1. name: String [br]
## 2. registry_code: String [br]
## 3. legal_form: String [br]
## 4. status: String [br]
## 5. since: String [br]
## 6. sector: String [br]
## 7. employees: int [br]
## 8. turnover: int [br]
## 9. health: String [br]
func seed_tenant(tunnus: String, name: String, registry_code: String, legal_form: String, status: String, since: String, sector: String, employees: int, turnover: int, health: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('seed_tenant', [tunnus, name, registry_code, legal_form, status, since, sector, employees, turnover, health], [&'string', &'string', &'string', &'string', &'string', &'string', &'string', &'u32', &'u64', &'string'], &'')

## 0. name: String [br]
func set_name(name: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('set_name', [name], [&'string'], &'')

## 0. bid_id: int [br]
func withdraw_bid(bid_id: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('withdraw_bid', [bid_id], [&'u64'], &'')

