# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
extends Node
#SpacetimeDB Autoload

var Vakuraamat: VakuraamatModuleClient

func _init() -> void:
	Vakuraamat = preload('res://spacetime_bindings/schema/module_vakuraamat_client.gd').new()
	add_child(Vakuraamat)
